-- Atualizar template CCI com os 105 itens corretos do documento MMS.BR.BA.FOR.007
UPDATE checklist_templates
SET 
  itens = '[
    {"id": 1, "nome": "NÍVEL DO LÍQUIDO DE ARREFECIMENTO", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 1},
    {"id": 2, "nome": "NÍVEL ÓLEO DE MOTOR", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 2},
    {"id": 3, "nome": "VAZAMENTOS EM GERAL", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 3},
    {"id": 4, "nome": "ESTADO DOS PNEUS (PRESSÃO E DESGASTE)", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 4},
    {"id": 5, "nome": "VERIFICAÇÃO DE DANOS EXTERNOS", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 5},
    {"id": 6, "nome": "NÍVEL COMBUSTÍVEL", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 6},
    {"id": 7, "nome": "FARÓIS", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 7},
    {"id": 8, "nome": "LANTERNAS", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 8},
    {"id": 9, "nome": "PISCA-PISCA", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 9},
    {"id": 10, "nome": "LUZ DE FREIO", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 10},
    {"id": 11, "nome": "LUZ DE RÉ", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 11},
    {"id": 12, "nome": "STROBO", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 12},
    {"id": 13, "nome": "GIROFLEX", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 13},
    {"id": 14, "nome": "SIRENE", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 14},
    {"id": 15, "nome": "RETROVISORES", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 15},
    {"id": 16, "nome": "PARA-BRISA", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 16},
    {"id": 17, "nome": "LIMPADORES DE PARA-BRISA", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 17},
    {"id": 18, "nome": "BUZINA", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 18},
    {"id": 19, "nome": "PORTAS E FECHADURAS", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 19},
    {"id": 20, "nome": "ESTEPE", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 20},
    {"id": 21, "nome": "MACACO", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 21},
    {"id": 22, "nome": "CHAVE DE RODA", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 22},
    {"id": 23, "nome": "TRIÂNGULO DE SINALIZAÇÃO", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 23},
    {"id": 24, "nome": "CONE DE SINALIZAÇÃO", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 24},
    {"id": 25, "nome": "QUILOMETRAGEM ATUAL", "categoria": "CABINE", "tipo": "medida", "obrigatorio": true, "ordem": 25, "unidade": "km"},
    {"id": 26, "nome": "NÍVEL DE COMBUSTÍVEL (PAINEL)", "categoria": "CABINE", "tipo": "verificacao", "obrigatorio": true, "ordem": 26},
    {"id": 27, "nome": "LUZES DE ADVERTÊNCIA NO PAINEL", "categoria": "CABINE", "tipo": "verificacao", "obrigatorio": true, "ordem": 27},
    {"id": 28, "nome": "FUNCIONAMENTO DO VELOCÍMETRO", "categoria": "CABINE", "tipo": "verificacao", "obrigatorio": true, "ordem": 28},
    {"id": 29, "nome": "FUNCIONAMENTO DO TACÔMETRO", "categoria": "CABINE", "tipo": "verificacao", "obrigatorio": true, "ordem": 29},
    {"id": 30, "nome": "CINTOS DE SEGURANÇA", "categoria": "CABINE", "tipo": "verificacao", "obrigatorio": true, "ordem": 30},
    {"id": 31, "nome": "BANCOS E AJUSTES", "categoria": "CABINE", "tipo": "verificacao", "obrigatorio": true, "ordem": 31},
    {"id": 32, "nome": "AR CONDICIONADO", "categoria": "CABINE", "tipo": "verificacao", "obrigatorio": true, "ordem": 32},
    {"id": 33, "nome": "AQUECEDOR", "categoria": "CABINE", "tipo": "verificacao", "obrigatorio": true, "ordem": 33},
    {"id": 34, "nome": "RÁDIO COMUNICADOR", "categoria": "CABINE", "tipo": "verificacao", "obrigatorio": true, "ordem": 34},
    {"id": 35, "nome": "GPS", "categoria": "CABINE", "tipo": "verificacao", "obrigatorio": true, "ordem": 35},
    {"id": 36, "nome": "KIT PRIMEIROS SOCORROS", "categoria": "CABINE", "tipo": "verificacao", "obrigatorio": true, "ordem": 36},
    {"id": 37, "nome": "EXTINTOR DE INCÊNDIO DA CABINE", "categoria": "CABINE", "tipo": "verificacao", "obrigatorio": true, "ordem": 37},
    {"id": 38, "nome": "BATERIA", "categoria": "ELÉTRICA", "tipo": "verificacao", "obrigatorio": true, "ordem": 38},
    {"id": 39, "nome": "ALTERNADOR", "categoria": "ELÉTRICA", "tipo": "verificacao", "obrigatorio": true, "ordem": 39},
    {"id": 40, "nome": "SISTEMA DE IGNIÇÃO", "categoria": "ELÉTRICA", "tipo": "verificacao", "obrigatorio": true, "ordem": 40},
    {"id": 41, "nome": "CONEXÕES ELÉTRICAS", "categoria": "ELÉTRICA", "tipo": "verificacao", "obrigatorio": true, "ordem": 41},
    {"id": 42, "nome": "FUSÍVEIS", "categoria": "ELÉTRICA", "tipo": "verificacao", "obrigatorio": true, "ordem": 42},
    {"id": 43, "nome": "BOMBA DE ÁGUA (FUNCIONAMENTO)", "categoria": "SISTEMA CONTRA INCÊNDIO", "tipo": "verificacao", "obrigatorio": true, "ordem": 43},
    {"id": 44, "nome": "NÍVEL DO TANQUE DE ÁGUA", "categoria": "SISTEMA CONTRA INCÊNDIO", "tipo": "verificacao", "obrigatorio": true, "ordem": 44},
    {"id": 45, "nome": "NÍVEL DO TANQUE DE ESPUMA LGE", "categoria": "SISTEMA CONTRA INCÊNDIO", "tipo": "verificacao", "obrigatorio": true, "ordem": 45},
    {"id": 46, "nome": "MANGUEIRAS (ESTADO GERAL)", "categoria": "SISTEMA CONTRA INCÊNDIO", "tipo": "verificacao", "obrigatorio": true, "ordem": 46},
    {"id": 47, "nome": "ESGUICHOS", "categoria": "SISTEMA CONTRA INCÊNDIO", "tipo": "verificacao", "obrigatorio": true, "ordem": 47},
    {"id": 48, "nome": "VÁLVULAS (FUNCIONAMENTO)", "categoria": "SISTEMA CONTRA INCÊNDIO", "tipo": "verificacao", "obrigatorio": true, "ordem": 48},
    {"id": 49, "nome": "CANHÃO MONITOR", "categoria": "SISTEMA CONTRA INCÊNDIO", "tipo": "verificacao", "obrigatorio": true, "ordem": 49},
    {"id": 50, "nome": "SISTEMA DE PROPORCIONAMENTO DE ESPUMA", "categoria": "SISTEMA CONTRA INCÊNDIO", "tipo": "verificacao", "obrigatorio": true, "ordem": 50},
    {"id": 51, "nome": "MANÔMETROS E INDICADORES", "categoria": "SISTEMA CONTRA INCÊNDIO", "tipo": "verificacao", "obrigatorio": true, "ordem": 51},
    {"id": 52, "nome": "CHASSI (INSPEÇÃO VISUAL)", "categoria": "PARTE INFERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 52},
    {"id": 53, "nome": "SUSPENSÃO", "categoria": "PARTE INFERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 53},
    {"id": 54, "nome": "SISTEMA DE FREIOS", "categoria": "PARTE INFERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 54},
    {"id": 55, "nome": "PASTILHAS/LONAS DE FREIO", "categoria": "PARTE INFERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 55},
    {"id": 56, "nome": "DISCOS/TAMBORES DE FREIO", "categoria": "PARTE INFERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 56},
    {"id": 57, "nome": "FLUIDO DE FREIO", "categoria": "PARTE INFERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 57},
    {"id": 58, "nome": "SISTEMA DE TRANSMISSÃO", "categoria": "PARTE INFERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 58},
    {"id": 59, "nome": "CÁRDAN", "categoria": "PARTE INFERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 59},
    {"id": 60, "nome": "DIFERENCIAL", "categoria": "PARTE INFERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 60},
    {"id": 61, "nome": "ÓLEO DE TRANSMISSÃO", "categoria": "PARTE INFERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 61},
    {"id": 62, "nome": "SISTEMA DE ESCAPE", "categoria": "PARTE INFERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 62},
    {"id": 63, "nome": "TANQUE DE COMBUSTÍVEL", "categoria": "PARTE INFERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 63},
    {"id": 64, "nome": "PROTEÇÕES INFERIORES", "categoria": "PARTE INFERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 64},
    {"id": 65, "nome": "COMPARTIMENTOS DE ARMAZENAMENTO", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 65},
    {"id": 66, "nome": "FECHADURAS DOS COMPARTIMENTOS", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 66},
    {"id": 67, "nome": "ESCADAS", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 67},
    {"id": 68, "nome": "SUPORTES PARA EQUIPAMENTOS", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 68},
    {"id": 69, "nome": "ENROLADORES DE MANGUEIRA", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 69},
    {"id": 70, "nome": "ILUMINAÇÃO DE CENA", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 70},
    {"id": 71, "nome": "GERADOR AUXILIAR", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 71},
    {"id": 72, "nome": "TANQUE DE ÁGUA (ESTRUTURA EXTERNA)", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 72},
    {"id": 73, "nome": "TANQUE DE ESPUMA (ESTRUTURA EXTERNA)", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 73},
    {"id": 74, "nome": "PINTURA E IDENTIFICAÇÕES", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 74},
    {"id": 75, "nome": "ADESIVOS DE SEGURANÇA", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 75},
    {"id": 76, "nome": "EXTINTOR PÓ BC 04 KG", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 76},
    {"id": 77, "nome": "EXTINTOR PÓ ABC 06 KG", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 77},
    {"id": 78, "nome": "EXTINTOR CO2 06 KG", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 78},
    {"id": 79, "nome": "MANGUEIRA 38MM (1 1/2)", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 79},
    {"id": 80, "nome": "MANGUEIRA 63MM (2 1/2)", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 80},
    {"id": 81, "nome": "ESGUICHO REGULÁVEL 38MM", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 81},
    {"id": 82, "nome": "ESGUICHO REGULÁVEL 63MM", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 82},
    {"id": 83, "nome": "CHAVE STORZ 38MM", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 83},
    {"id": 84, "nome": "CHAVE STORZ 63MM", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 84},
    {"id": 85, "nome": "DERIVANTE DUPLO 63MM X 38MM", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 85},
    {"id": 86, "nome": "DERIVANTE TRIPLO 63MM X 38MM", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 86},
    {"id": 87, "nome": "REDUÇÃO 63MM X 38MM", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 87},
    {"id": 88, "nome": "TAMPÃO 38MM", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 88},
    {"id": 89, "nome": "TAMPÃO 63MM", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 89},
    {"id": 90, "nome": "CHAVE DE HIDRANTE", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 90},
    {"id": 91, "nome": "PÁ", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 91},
    {"id": 92, "nome": "PICARETA", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 92},
    {"id": 93, "nome": "MACHADO", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 93},
    {"id": 94, "nome": "LANTERNA", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 94},
    {"id": 95, "nome": "CORDA DE SEGURANÇA", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 95},
    {"id": 96, "nome": "PROTETOR AURICULAR", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 96},
    {"id": 97, "nome": "ÓCULOS DE PROTEÇÃO", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 97},
    {"id": 98, "nome": "LUVAS DE PROTEÇÃO", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 98},
    {"id": 99, "nome": "CAPACETE", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 99},
    {"id": 100, "nome": "BOTA DE SEGURANÇA", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 100},
    {"id": 101, "nome": "CONJUNTO DE EPR (EQUIPAMENTO DE PROTEÇÃO RESPIRATÓRIA)", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 101},
    {"id": 102, "nome": "ROUPA ALUMINIZADA", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 102},
    {"id": 103, "nome": "KIT DE FERRAMENTAS", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 103},
    {"id": 104, "nome": "ABRAÇADEIRAS E FIXAÇÕES", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 104},
    {"id": 105, "nome": "GANCHO TRASEIRO PARA REBOQUE", "categoria": "PARTE SUPERIOR", "tipo": "verificacao", "obrigatorio": true, "ordem": 105}
  ]'::jsonb,
  updated_at = now()
WHERE tipo_viatura = 'CCI' AND ativo = true;