-- Fase 1: Criar Template CRS completo com base no documento MMS.BR.BA.FOR.014
INSERT INTO public.checklist_templates (nome, tipo_viatura, categoria, ativo, itens)
VALUES (
  'Checklist CRS (Carro de Resgate e Salvamento)',
  'CRS',
  'Veículo Especializado',
  true,
  '[
    {"id": "crs_ext_1", "nome": "NÍVEL COMBUSTÍVEL", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 1},
    {"id": "crs_ext_2", "nome": "NÍVEL ÓLEO MOTOR", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 2},
    {"id": "crs_ext_3", "nome": "NÍVEL LÍQUIDO DE ARREFECIMENTO", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 3},
    {"id": "crs_ext_4", "nome": "NÍVEL ÓLEO HIDRÁULICO", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 4},
    {"id": "crs_ext_5", "nome": "NÍVEL DO RESERVATÓRIO DE FREIO", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 5},
    {"id": "crs_ext_6", "nome": "PRESSÃO DOS PNEUS", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 6},
    {"id": "crs_ext_7", "nome": "LANTERNA FAROL ALERTA DIANTEIRO", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 7},
    {"id": "crs_ext_8", "nome": "LANTERNA FAROL ALERTA TRASEIRO", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 8},
    {"id": "crs_ext_9", "nome": "LANTERNA FREIO", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 9},
    {"id": "crs_ext_10", "nome": "SETA/PISCA ALERTA", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 10},
    {"id": "crs_ext_11", "nome": "LUZ DE RÉ", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 11},
    {"id": "crs_ext_12", "nome": "ILUMINAÇÃO DA PLACA", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 12},
    {"id": "crs_ext_13", "nome": "CONDIÇÕES DOS PNEUS", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 13},
    {"id": "crs_ext_14", "nome": "LIMPADOR DE PARA-BRISA", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 14},
    {"id": "crs_ext_15", "nome": "ESTADO GERAL DA CARROCERIA", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 15},
    {"id": "crs_ext_16", "nome": "VAZAMENTOS EM GERAL", "categoria": "CHECK EXTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 16},
    
    {"id": "crs_int_1", "nome": "LUZES E SIRENE", "categoria": "CHECK INTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 17},
    {"id": "crs_int_2", "nome": "PAINEL SEM ALERTAS", "categoria": "CHECK INTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 18},
    {"id": "crs_int_3", "nome": "VELOCÍMETRO FUNCIONANDO", "categoria": "CHECK INTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 19},
    {"id": "crs_int_4", "nome": "FREIO DE SERVIÇO", "categoria": "CHECK INTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 20},
    {"id": "crs_int_5", "nome": "FREIO DE ESTACIONAMENTO", "categoria": "CHECK INTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 21},
    {"id": "crs_int_6", "nome": "CINTO DE SEGURANÇA", "categoria": "CHECK INTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 22},
    {"id": "crs_int_7", "nome": "BUZINA", "categoria": "CHECK INTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 23},
    {"id": "crs_int_8", "nome": "RETROVISORES", "categoria": "CHECK INTERNO", "tipo": "verificacao", "obrigatorio": true, "ordem": 24},
    
    {"id": "crs_sup_1", "nome": "EPR 01", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 25},
    {"id": "crs_sup_2", "nome": "EPR 02", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 26},
    {"id": "crs_sup_3", "nome": "EPR 03", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 27},
    {"id": "crs_sup_4", "nome": "EPR 04", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 28},
    {"id": "crs_sup_5", "nome": "CILINDRO RESERVA 01", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 29},
    {"id": "crs_sup_6", "nome": "CILINDRO RESERVA 02", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 30},
    {"id": "crs_sup_7", "nome": "CILINDRO RESERVA 03", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 31},
    {"id": "crs_sup_8", "nome": "CABO GUIA 200M", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 32},
    {"id": "crs_sup_9", "nome": "CORDA VIDA 30M", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 33},
    {"id": "crs_sup_10", "nome": "RÁDIO HT 01", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 34},
    {"id": "crs_sup_11", "nome": "RÁDIO HT 02", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 35},
    {"id": "crs_sup_12", "nome": "RÁDIO MÓVEL", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 36},
    {"id": "crs_sup_13", "nome": "LANTERNA RECARREGÁVEL 01", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 37},
    {"id": "crs_sup_14", "nome": "LANTERNA RECARREGÁVEL 02", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 38},
    {"id": "crs_sup_15", "nome": "REFLETOR HOLOFOTE", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 39},
    {"id": "crs_sup_16", "nome": "EXTINTOR PQS 6KG", "categoria": "PARTE SUPERIOR/CONVÉS", "tipo": "verificacao", "obrigatorio": true, "ordem": 40},
    
    {"id": "crs_geral_1", "nome": "MARRETA 4KG", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 41},
    {"id": "crs_geral_2", "nome": "PICARETA", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 42},
    {"id": "crs_geral_3", "nome": "MACHADO", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 43},
    {"id": "crs_geral_4", "nome": "PÉ DE CABRA", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 44},
    {"id": "crs_geral_5", "nome": "CONJUNTO FERRAMENTAS MANUAIS", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 45},
    {"id": "crs_geral_6", "nome": "ESTILETE GRANDE", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 46},
    {"id": "crs_geral_7", "nome": "CUNHA MADEIRA GRANDE", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 47},
    {"id": "crs_geral_8", "nome": "CUNHA MADEIRA MÉDIA", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 48},
    {"id": "crs_geral_9", "nome": "CUNHA MADEIRA PEQUENA", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 49},
    {"id": "crs_geral_10", "nome": "ESPÁTULA RESGATE", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 50},
    {"id": "crs_geral_11", "nome": "SACOS PLÁSTICOS", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 51},
    {"id": "crs_geral_12", "nome": "FITA ZEBRADA", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 52},
    {"id": "crs_geral_13", "nome": "LUVA VAQUETA", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "par", "ordem": 53},
    {"id": "crs_geral_14", "nome": "CAPACETE RESGATE", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 54},
    {"id": "crs_geral_15", "nome": "ÓCULOS PROTEÇÃO", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 55},
    {"id": "crs_geral_16", "nome": "MANTA ALUMINIZADA", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 56},
    {"id": "crs_geral_17", "nome": "LONA PLÁSTICA", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 57},
    {"id": "crs_geral_18", "nome": "DETECTOR DE GASES", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 58},
    {"id": "crs_geral_19", "nome": "CÂMERA TERMAL", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 59},
    {"id": "crs_geral_20", "nome": "CONES SINALIZADORES", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 60},
    {"id": "crs_geral_21", "nome": "TRIÂNGULO SINALIZAÇÃO", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 61},
    {"id": "crs_geral_22", "nome": "MACACO HIDRÁULICO", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 62},
    {"id": "crs_geral_23", "nome": "CHAVE RODA", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 63},
    {"id": "crs_geral_24", "nome": "ESTEPE", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 64},
    {"id": "crs_geral_25", "nome": "ESCADA PROLONGÁVEL", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 65},
    {"id": "crs_geral_26", "nome": "ESCADA SINGELA", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 66},
    {"id": "crs_geral_27", "nome": "MANGUEIRA 1.1/2 POL", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "lance", "ordem": 67},
    {"id": "crs_geral_28", "nome": "MANGUEIRA 2.1/2 POL", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "lance", "ordem": 68},
    {"id": "crs_geral_29", "nome": "ESGUICHO REGULÁVEL", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 69},
    {"id": "crs_geral_30", "nome": "DERIVANTE DUPLO", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 70},
    {"id": "crs_geral_31", "nome": "CHAVE STORZ", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 71},
    {"id": "crs_geral_32", "nome": "MOTO-ABRASIVO", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 72},
    {"id": "crs_geral_33", "nome": "MOTO-SERRA", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 73},
    {"id": "crs_geral_34", "nome": "DESENCARCERADOR HIDRÁULICO", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 74},
    {"id": "crs_geral_35", "nome": "EXPANSOR HIDRÁULICO", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 75},
    {"id": "crs_geral_36", "nome": "CILINDRO RESGATE", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 76},
    {"id": "crs_geral_37", "nome": "BOMBA HIDRÁULICA MANUAL", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 77},
    {"id": "crs_geral_38", "nome": "KIT PRIMEIROS SOCORROS", "categoria": "CHECK LIST GERAL", "tipo": "verificacao", "obrigatorio": true, "ordem": 78},
    {"id": "crs_geral_39", "nome": "PRANCHA LONGA", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 79},
    {"id": "crs_geral_40", "nome": "COLAR CERVICAL REGULÁVEL", "categoria": "CHECK LIST GERAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 80}
  ]'::jsonb
);

-- Fase 2: Atualizar Template de Equipamentos com base no documento MMS.BR.BA.FOR.012
UPDATE public.checklist_templates
SET itens = '[
  {"id": "eq_epr_1", "nome": "EPR - EQUIPAMENTO DE PROTEÇÃO RESPIRATÓRIA", "categoria": "EPR", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 1},
  {"id": "eq_epr_2", "nome": "CILINDRO RESERVA", "categoria": "EPR", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 2},
  {"id": "eq_epr_3", "nome": "MÁSCARA FACIAL RESERVA", "categoria": "EPR", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 3},
  
  {"id": "eq_epi_1", "nome": "CAPACETE ESTRUTURAL", "categoria": "EPI ESTRUTURAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 4},
  {"id": "eq_epi_2", "nome": "BALACLAVA PROTEÇÃO", "categoria": "EPI ESTRUTURAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 5},
  {"id": "eq_epi_3", "nome": "JAQUETA ESTRUTURAL", "categoria": "EPI ESTRUTURAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 6},
  {"id": "eq_epi_4", "nome": "CALÇA ESTRUTURAL", "categoria": "EPI ESTRUTURAL", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 7},
  {"id": "eq_epi_5", "nome": "BOTA ESTRUTURAL", "categoria": "EPI ESTRUTURAL", "tipo": "contagem", "obrigatorio": true, "unidade": "par", "ordem": 8},
  {"id": "eq_epi_6", "nome": "LUVA ESTRUTURAL", "categoria": "EPI ESTRUTURAL", "tipo": "contagem", "obrigatorio": true, "unidade": "par", "ordem": 9},
  
  {"id": "eq_rad_1", "nome": "RÁDIO HT PORTÁTIL", "categoria": "RÁDIOS E COMUNICAÇÃO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 10},
  {"id": "eq_rad_2", "nome": "RÁDIO MÓVEL VEICULAR", "categoria": "RÁDIOS E COMUNICAÇÃO", "tipo": "verificacao", "obrigatorio": true, "ordem": 11},
  {"id": "eq_rad_3", "nome": "BATERIA RESERVA HT", "categoria": "RÁDIOS E COMUNICAÇÃO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 12},
  {"id": "eq_rad_4", "nome": "CARREGADOR RÁDIO", "categoria": "RÁDIOS E COMUNICAÇÃO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 13},
  
  {"id": "eq_ilum_1", "nome": "LANTERNA RECARREGÁVEL CAPACETE", "categoria": "ILUMINAÇÃO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 14},
  {"id": "eq_ilum_2", "nome": "LANTERNA MANUAL RECARREGÁVEL", "categoria": "ILUMINAÇÃO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 15},
  {"id": "eq_ilum_3", "nome": "REFLETOR HOLOFOTE PORTÁTIL", "categoria": "ILUMINAÇÃO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 16},
  {"id": "eq_ilum_4", "nome": "BASTÃO SINALIZADOR", "categoria": "ILUMINAÇÃO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 17},
  
  {"id": "eq_ferr_1", "nome": "MACHADO BOMBEIRO", "categoria": "FERRAMENTAS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 18},
  {"id": "eq_ferr_2", "nome": "PICARETA", "categoria": "FERRAMENTAS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 19},
  {"id": "eq_ferr_3", "nome": "PÉ DE CABRA", "categoria": "FERRAMENTAS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 20},
  {"id": "eq_ferr_4", "nome": "MARRETA 4KG", "categoria": "FERRAMENTAS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 21},
  {"id": "eq_ferr_5", "nome": "ALICATE CORTE", "categoria": "FERRAMENTAS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 22},
  {"id": "eq_ferr_6", "nome": "CHAVE INGLESA", "categoria": "FERRAMENTAS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 23},
  {"id": "eq_ferr_7", "nome": "CHAVE FENDA/PHILIPS", "categoria": "FERRAMENTAS", "tipo": "contagem", "obrigatorio": true, "unidade": "jogo", "ordem": 24},
  {"id": "eq_ferr_8", "nome": "CHAVE SEXTAVADA", "categoria": "FERRAMENTAS", "tipo": "contagem", "obrigatorio": true, "unidade": "jogo", "ordem": 25},
  {"id": "eq_ferr_9", "nome": "ESTILETE", "categoria": "FERRAMENTAS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 26},
  
  {"id": "eq_comb_1", "nome": "MANGUEIRA 1.1/2 POL", "categoria": "COMBATE A INCÊNDIO", "tipo": "contagem", "obrigatorio": true, "unidade": "lance", "ordem": 27},
  {"id": "eq_comb_2", "nome": "MANGUEIRA 2.1/2 POL", "categoria": "COMBATE A INCÊNDIO", "tipo": "contagem", "obrigatorio": true, "unidade": "lance", "ordem": 28},
  {"id": "eq_comb_3", "nome": "ESGUICHO REGULÁVEL 1.1/2", "categoria": "COMBATE A INCÊNDIO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 29},
  {"id": "eq_comb_4", "nome": "ESGUICHO REGULÁVEL 2.1/2", "categoria": "COMBATE A INCÊNDIO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 30},
  {"id": "eq_comb_5", "nome": "DERIVANTE DUPLO", "categoria": "COMBATE A INCÊNDIO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 31},
  {"id": "eq_comb_6", "nome": "DERIVANTE TRIPLO", "categoria": "COMBATE A INCÊNDIO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 32},
  {"id": "eq_comb_7", "nome": "CHAVE STORZ", "categoria": "COMBATE A INCÊNDIO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 33},
  {"id": "eq_comb_8", "nome": "MANGOTE SUCÇÃO", "categoria": "COMBATE A INCÊNDIO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 34},
  {"id": "eq_comb_9", "nome": "REDUTOR 2.1/2 X 1.1/2", "categoria": "COMBATE A INCÊNDIO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 35},
  {"id": "eq_comb_10", "nome": "ADAPTADOR STORZ", "categoria": "COMBATE A INCÊNDIO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 36},
  
  {"id": "eq_ext_1", "nome": "EXTINTOR PQS 6KG", "categoria": "EXTINTORES", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 37},
  {"id": "eq_ext_2", "nome": "EXTINTOR PQS 12KG", "categoria": "EXTINTORES", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 38},
  {"id": "eq_ext_3", "nome": "EXTINTOR CO2 6KG", "categoria": "EXTINTORES", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 39},
  {"id": "eq_ext_4", "nome": "EXTINTOR ÁGUA PRESSURIZADA", "categoria": "EXTINTORES", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 40},
  
  {"id": "eq_corda_1", "nome": "CORDA VIDA 30M", "categoria": "CORDAS E CABOS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 41},
  {"id": "eq_corda_2", "nome": "CABO GUIA 50M", "categoria": "CORDAS E CABOS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 42},
  {"id": "eq_corda_3", "nome": "CABO GUIA 100M", "categoria": "CORDAS E CABOS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 43},
  {"id": "eq_corda_4", "nome": "CORDA ESTÁTICA 11MM", "categoria": "CORDAS E CABOS", "tipo": "contagem", "obrigatorio": true, "unidade": "m", "ordem": 44},
  {"id": "eq_corda_5", "nome": "FITA TUBULAR 25MM", "categoria": "CORDAS E CABOS", "tipo": "contagem", "obrigatorio": true, "unidade": "m", "ordem": 45},
  {"id": "eq_corda_6", "nome": "MOSQUETÃO OVAL", "categoria": "CORDAS E CABOS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 46},
  {"id": "eq_corda_7", "nome": "MOSQUETÃO HMS", "categoria": "CORDAS E CABOS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 47},
  {"id": "eq_corda_8", "nome": "DESCENSOR OITO", "categoria": "CORDAS E CABOS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 48},
  {"id": "eq_corda_9", "nome": "FREIO ATC", "categoria": "CORDAS E CABOS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 49},
  {"id": "eq_corda_10", "nome": "CADEIRINHA RESGATE", "categoria": "CORDAS E CABOS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 50},
  
  {"id": "eq_esc_1", "nome": "ESCADA PROLONGÁVEL", "categoria": "ESCADAS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 51},
  {"id": "eq_esc_2", "nome": "ESCADA SINGELA", "categoria": "ESCADAS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 52},
  {"id": "eq_esc_3", "nome": "ESCADA GANCHO TELHADO", "categoria": "ESCADAS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 53},
  
  {"id": "eq_det_1", "nome": "DETECTOR GASES 4 EM 1", "categoria": "DETECÇÃO", "tipo": "verificacao", "obrigatorio": true, "ordem": 54},
  {"id": "eq_det_2", "nome": "CÂMERA TÉRMICA", "categoria": "DETECÇÃO", "tipo": "verificacao", "obrigatorio": true, "ordem": 55},
  {"id": "eq_det_3", "nome": "MEDIDOR CO AMBIENTE", "categoria": "DETECÇÃO", "tipo": "verificacao", "obrigatorio": true, "ordem": 56},
  
  {"id": "eq_sin_1", "nome": "CONE SINALIZAÇÃO", "categoria": "SINALIZAÇÃO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 57},
  {"id": "eq_sin_2", "nome": "TRIÂNGULO SINALIZAÇÃO", "categoria": "SINALIZAÇÃO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 58},
  {"id": "eq_sin_3", "nome": "FITA ZEBRADA", "categoria": "SINALIZAÇÃO", "tipo": "contagem", "obrigatorio": true, "unidade": "rolo", "ordem": 59},
  {"id": "eq_sin_4", "nome": "BANDEIROLA SINALIZAÇÃO", "categoria": "SINALIZAÇÃO", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 60},
  
  {"id": "eq_div_1", "nome": "LONA PLÁSTICA", "categoria": "DIVERSOS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 61},
  {"id": "eq_div_2", "nome": "MANTA ALUMINIZADA", "categoria": "DIVERSOS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 62},
  {"id": "eq_div_3", "nome": "SACO PLÁSTICO RECOLHIMENTO", "categoria": "DIVERSOS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 63},
  {"id": "eq_div_4", "nome": "CUNHA MADEIRA GRANDE", "categoria": "DIVERSOS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 64},
  {"id": "eq_div_5", "nome": "CUNHA MADEIRA MÉDIA", "categoria": "DIVERSOS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 65},
  {"id": "eq_div_6", "nome": "CUNHA MADEIRA PEQUENA", "categoria": "DIVERSOS", "tipo": "contagem", "obrigatorio": true, "unidade": "un", "ordem": 66}
]'::jsonb,
nome = 'Checklist de Equipamentos Completo',
updated_at = now()
WHERE tipo_viatura = 'EQUIPAMENTOS' AND ativo = true;